<section id="about">
	<div class="container">
		<h1><a href="#" class="anchor">What <strong>About</strong> me?</a></h1>
		<article id="me">
		<h2>My name is Mathieu, I’m a french developer based in Lyon!</h2>
			<p>I feel passionate about intuitive products and meticulous visual interfaces. To me, programming is like writing music: creativity, reflexion, and simplicity are the keys to build websites the best they can be.</p>
			<p>I look for creative ways to push the boundaries of website front-end code without compromising on browser performance, responsivity, and accessibility.
			I strongly believe that the best user experience is obtained only when every pixel has a purpose.</p>
			<p>I am a dreamer and a fanatic of all digital things. I write code and improve my design and skills every day, and keeping myself updated is natural and exciting for me.</p>
			<p>When I’ not coding, you can surelly find me at the gym, playing music, sitting in a movie theater, or visiting modern art museums to find inspirations in my works. Oh and I love travel around the world by the way!</p>
		</article>
	</div>	

	<article id="sound">
		<h2>Enjoy some <strong>beats</strong> I made few time ago</h2>
		<iframe width="50%" height="350" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/400329743&amp;color=%2334daeb&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;show_teaser=true"></iframe>
	</article>
</section>

<section id="skills">
	<div class="container">
		<h1>My main Dev <strong>skills</strong></h1>
		<article class="skills">
		<h2>If you want to make me a better (or a worst) developper, just play with my skills</h2>

			<ul>
				<li>
					<label for="round">HTML</label>
					<input type="text" name="round" class="round" data-min="0" data-max="100" value="75">
				</li>
				<li>
					<label for="round">CSS</label>
					<input type="text" name="round" class="round" data-min="0" data-max="100" value="80">
				</li>
				<li>
					<label for="round">JavaScript</label>
					<input type="text" name="round" class="round" data-min="0" data-max="100" value="70">
				</li>
				<li>
					<label for="round">PHP</label>
					<input type="text" name="round" class="round" data-min="0" data-max="100" value="70">
				</li>
				<li>
					<label for="round">MySql</label>
					<input type="text" name="round" class="round" data-min="0" data-max="100" value="75">
				</li>	
			</ul>
		</article>
	</div>
</section>

<div class="scrollTop">
	<a href="#" id="scrollTop"><i class="fa fa-long-arrow-up" aria-hidden="true"></i></a>
</div>

