<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Your SVG</title>
    <link href="https://fonts.googleapis.com/css?family=Khula|Pacifico" rel="stylesheet">
    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/style.css">
    <script src="https://code.jquery.com/jquery-3.2.1.js"></script>
    <script src="js/main.js"></script>
</head>
<body>
<main>
    <!-- splash screen -->
    <?php if (empty($_POST)) : ?>
        <h1 class="title">Make your own SVG shape</h1>
    <?php endif; ?>

    <section class="form">
    <h1 class="form-title"><a href="index.php">Click here to draw a brand new shape</a></h1>
    
    <!-- Formulaire d'ajout de tâche -->
    <form id="form" action="index.php" method="POST">
        <legend>Lets Draw!</legend>
            <ul>
                <li>
                    <label>
                        Choose the shape family
                         <select class="family" name="family">
                            <option selected value="rectangle">rectangle</option>
                            <option value="square">square</option>
                            <option value="ellipse">ellipse</option>
                            <option value="circle">circle</option>
                            <option value="triangle">triangle</option>
                          </select>
                    </label>
                 </li>
                <li>
                    <label>
                    Enter a number for X axe
                    <input required id="X" name="X" type="number" value="0" min="0">
                    </label>
                </li>
                <li>
                    <label>
                    Enter a number for Y axe
                    <input required id="Y" name="Y" type="number" value="0" min="0">
                    </label>
                </li>
                <li>
                    <label>
                        Choose a color
                         <input id="color" type="color" value="#ff0000" name="color">
                    </label>
                </li>
                <li>
                    <label>
                    Enter an opacity
                    <input class="opacity" required id="opacity" name="opacity" type="range" min="0" max="1" step="0.1">
                    </label>
                </li>
            </ul>
            <ul class="shape-option">
                
            </ul>
            <ul class="button">
                <li>
                    <input id="validDraw" type="submit" value="Draw" >
                </li>
                <li>
                    <input id="erase" type="button" value="Erase" >
                </li>
            </ul>
        </form>
    </section>   


<section id="svg">
  <div id="svg-container">
    <svg viewBox="0 0 500 500" preserveAspectRatio="xMinYMin meet" width="100%" height="100%">
        
        <!-- lance la méthode draw de l'objet shape -->
        <?php 
            if ($_POST) 
            {
                $shape->draw();
            }
        ?>
    </svg>
  </div>  
</section>
</main> 
</body>
</html>
